# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content on FTP folder

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['modx']

jobs:
  # Single deploy job since we're just deploying
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action
    #environment:
      #name: github-pages
      #url: ${{ steps.deployment.outputs.page_url }}
    env:
      MODX_BASE_PATH: "/ui/dist/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run prod
      - name: SFTP-Deploy-Action
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          sftp_only: true
          remote_path: './c2rloga4.beget.tech/public_html/ui'
          local_path: './dist'
          delete_remote_files: false
